### ISSUE TITLE
Alignment of QR codes side by side

### ISSUE THREAD

**Issue by paniash** [paniash/website#5]
Currently the website just does a basic workaround of placing one QR code below the other (as shown), however, this doesn't look very aesthetic.

![pic-selected-211230-1311-04](https://user-images.githubusercontent.com/59497618/147731462-73038431-5e31-4031-af71-f2c8f317b3ff.png)

The end result is to be along the lines of this:

![pic-selected-211230-1312-47](https://user-images.githubusercontent.com/59497618/147731561-8cb5cf39-8d92-4830-bab6-e7f2a37157c8.png)

Any suggestions? @tlienart

**Comment by tlienart** [comment]
this is pure HTML + CSS stuff. Have a look at this https://www.w3schools.com/howto/howto_css_cards.asp which is basically the same idea. I'd start by first copy pasting their stuff into a HTML raw block 

```
~~~
...the HTML here...
~~~
```

then once you're happy with the result you can start extracting the divs using `@@...` to make this clearer (though you don't have to, you can leave things as they are)

**Comment by paniash** [comment]
@tlienart Thanks! Fixed in 00122be.
